### ISSUE TITLE
Coloring for Markdown

### ISSUE THREAD

**Issue by jensgro** [Relaxed-Theme/atom-relaxed-syntax#2]
I installed this nice theme in Atom but unfortunately it lacked colorization for Markdown. Since I need this very often: is there a time frame for delivering the colorization of Markdown?

**Comment by mischah** [comment]
Hej Jens,

what exactly are you missing?
Could you provide a screenshot?

It looks like this on my screen:
![image](https://user-images.githubusercontent.com/441011/39565474-5f271f96-4eb8-11e8-8d3c-3a512bc05bdd.png)
![image](https://user-images.githubusercontent.com/441011/39565490-742f7d02-4eb8-11e8-8c7f-e89e7cd99371.png)

**Comment by jensgro** [comment]
Strange, one document looks bad, another good in my case. The bad one looks like this:
![grafik](https://user-images.githubusercontent.com/214849/39565674-2720f58a-4eb9-11e8-8732-913018cce0bc.png)

Obviously it's a problem with my file. Sorry.

**Comment by mischah** [comment]
No problem ☺️
